export const rOrderData = [
  {
    orderId: "1",
    customer: "Amal Perera",
    Location: "12/5A, Kaluthara, Uthura",
    OrderItems: "Pizza - 1, Kothu -5",
    price: "9000.00",
    supplier: "Amal Perera",
    Status: "Pending",
    dTime: "14:20",
  },
  {
    orderId: "1",
    customer: "Amal Perera",
    Location: "12/5A, Kaluthara, Uthura",
    OrderItems: "Pizza - 1, Kothu -5",
    price: "9000.00",
    supplier: "Amal Perera",
    Status: "Pending",
    dTime: "14:20",
  },
  {
    orderId: "1",
    customer: "Amal Perera",
    Location: "12/5A, Kaluthara, Uthura",
    OrderItems: "Pizza - 1, Kothu -5",
    price: "9000.00",
    supplier: "Amal Perera",
    Status: "Pending",
    dTime: "14:20",
  },
  {
    orderId: "1",
    customer: "Amal Perera",
    Location: "12/5A, Kaluthara, Uthura",
    OrderItems: "Pizza - 1, Kothu -5",
    price: "9000.00",
    supplier: "Amal Perera",
    Status: "Pending",
    dTime: "14:20",
  },
  {
    orderId: "1",
    customer: "Amal Perera",
    Location: "12/5A, Kaluthara, Uthura",
    OrderItems: "Pizza - 1, Kothu -5",
    price: "9000.00",
    supplier: "Amal Perera",
    Status: "Pending",
    dTime: "14:20",
  },
  {
    orderId: "1",
    customer: "Amal Perera",
    Location: "12/5A, Kaluthara, Uthura",
    OrderItems: "Pizza - 1, Kothu -5",
    price: "9000.00",
    supplier: "Amal Perera",
    Status: "Pending",
    dTime: "14:20",
  },
  {
    orderId: "1",
    customer: "Amal Perera",
    Location: "12/5A, Kaluthara, Uthura",
    OrderItems: "Pizza - 1, Kothu -5",
    price: "9000.00",
    supplier: "Amal Perera",
    Status: "Pending",
    dTime: "14:20",
  },
];
